### ISSUE TITLE
Process `RIBAP:ilp_refinement (8)` terminated with an error exit status (1)

### ISSUE THREAD

**Issue by Andrewab9** [hoelzer-lab/ribap#59]
Hi there,
I get this error during the ilps_refinement:

sudo /home/enrico/.cargo/bin/nextflow run hoelzer-lab/ribap -r 1.0.2 --fasta '*.fasta' --cores 30 --max_cores 30 --memory 100.GB -profile local,docker -w work --output ribap-results -resume

executor >  local (9)
executor >  local (9)
[ac/4c700e] process > RIBAP:rename (8)            [100%] 13 of 13, cached: 13 ✔
[fb/cf620e] process > RIBAP:prokka (4)            [100%] 13 of 13, cached: 13 ✔
[56/c44eb0] process > RIBAP:strain_ids            [100%] 1 of 1, cached: 1 ✔
[1e/e1602f] process > RIBAP:roary (2)             [100%] 5 of 5, cached: 5 ✔
[b7/18cdbe] process > RIBAP:mmseqs2               [100%] 1 of 1, cached: 1 ✔
[86/c9e361] process > RIBAP:mmseqs2tsv            [100%] 1 of 1, cached: 1 ✔
[3d/51364e] process > RIBAP:ilp_refinement (5)    [100%] 2 of 2, failed: 2

ERROR ~ Error executing process > 'RIBAP:ilp_refinement (8)'

Caused by:
  Process `RIBAP:ilp_refinement (8)` terminated with an error exit status (1)

Command executed:

  derive_ilp_solutions.py --tmlim 240 --max --indel mmseqs_compressed_chunk7.pkl

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/root/.nextflow/assets/hoelzer-lab/ribap/bin/derive_ilp_solutions.py", line 151, in <module>
    File "/root/.nextflow/assets/hoelzer-lab/ribap/bin/derive_ilp_solutions.py", line 76, in main
    File "/root/.nextflow/assets/hoelzer-lab/ribap/bin/derive_ilp_solutions.py", line 113, in pool_workload
    File "/root/.nextflow/assets/hoelzer-lab/ribap/bin/ILPBuilder.py", line 128, in generate_lp
  OSError: [Errno 24] Too many open files: './GMLHAKDO-vs-OOGOGPEF_1018.ilp'

Work dir:
  /home/enrico/Projects/domenico/s_aureus/redundans_pilon_pilon/work/91/857bba7d2381dbf9c0662364ae0d4e

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details

I've tried changing --chunks from 1 to 8; changing --cores, --max_cores and --memory. I've tried to set also to its maximum value (ulimit -n 1048576) but it doesn't work too.
Hope you can help me and thank you for making ribap!

**Comment by hoelzer** [comment]
Hey @Andrewab9, thanks for your interest in the pipeline!

Sorry that it fails. Can you share the 13 FASTA files? Or is it confidential data? I want to give it a try and to reproduce your problem.

Actually, changing `--chunks` would have also been my first idea, but you already tried that.

**Comment by hoelzer** [comment]
Closing bc no further response. Pls feel free to reopen if problem persists.
