### ISSUE TITLE
Unable to find image 'nanozoo/python_ribap:3.7--33a36cd' locally

### ISSUE THREAD

**Issue by shlomobl** [hoelzer-lab/ribap#71]
Hi again,
I looked like it was working alright, but then I got the error below.
==> Unable to find image 'nanozoo/python_ribap:3.7--33a36cd' locally
Any ideas?
Thanks!

```
shlomo@shlomo-HP-Z840:/media/shlomo/DATADRIVE3/CoNS/CoNS_FINAL$ sudo nextflow run hoelzer-lab/ribap -r 1.1.1 --fasta './Pilon_scaffolds_200/*.fasta' --gcode 11 --reference aureus_RF122.gb --tree --core_perc 99 --output '/media/shlomo/DATADRIVE3/CoNS/CoNS_FINAL/RIBAP' --keepILPs -w /media/shlomo/DATADRIVE3/CoNS/CoNS_FINAL/RIBAP_work -profile local,docker
\
 N E X T F L O W   ~  version 24.10.1

Pulling hoelzer-lab/ribap ...
 downloaded from https://github.com/hoelzer-lab/ribap.git
Launching `https://github.com/hoelzer-lab/ribap` [maniac_pauling] DSL2 - revision: a61ffa369a [1.1.1]

 
Profile: local,docker
 
Current User: root
Nextflow-version: 24.10.1
Starting time: 18-11-2024 12:21 UTC
Workdir location (intermediate files):
  /media/shlomo/DATADRIVE3/CoNS/CoNS_FINAL/RIBAP_work
Output dir name:
  /media/shlomo/DATADRIVE3/CoNS/CoNS_FINAL/RIBAP
 
WARNING: ILPs will be stored which can take a lot of disk space!
executor >  local (463)
[1e/3a2445] process > RIBAP:rename (SSA8530)      [100%] 223 of 223 ✔
[c2/a6a664] process > RIBAP:prokka (223)          [100%] 223 of 223 ✔
[10/d6133a] process > RIBAP:strain_ids            [100%] 1 of 1 ✔
[e6/e251ef] process > RIBAP:roary (1)             [100%] 5 of 5 ✔
[c4/09b2dd] process > RIBAP:mmseqs2               [100%] 1 of 1 ✔
[c7/9e51c7] process > RIBAP:mmseqs2tsv            [100%] 1 of 1 ✔
[e2/df28ef] process > RIBAP:ilp_refinement (9)    [ 11%] 1 of 9
[-        ] process > RIBAP:combine_roary_ilp     -
[-        ] process > RIBAP:prepare_msa           -
[-        ] process > RIBAP:mafft                 -
[-        ] process > RIBAP:fasttree              -
[-        ] process > RIBAP:nw_display            -
[-        ] process > RIBAP:generate_html         -
[-        ] process > RIBAP:generate_upsetr_input -
[-        ] process > RIBAP:upsetr                -
[-        ] process > RIBAP:filter_alignment      -
[-        ] process > RIBAP:nexus_core            -
[-        ] process > RIBAP:iqtree                -
ERROR ~ Error executing process > 'RIBAP:ilp_refinement (7)'

Caused by:
  Process `RIBAP:ilp_refinement (7)` terminated with an error exit status (1)


Command executed:

  derive_ilp_solutions.py --tmlim 240 --max --indel mmseqs_compressed_chunk6.pkl --keep

Command exit status:
  1

Command output:
  (empty)

Command error:
  Unable to find image 'nanozoo/python_ribap:3.7--33a36cd' locally
  3.7--33a36cd: Pulling from nanozoo/python_ribap
  3f4ca61aafcd: Pulling fs layer
  69a5d9e1ecd6: Pulling fs layer
  7b4354700ca4: Pulling fs layer
  c7f57f419954: Pulling fs layer
  f427023642b5: Pulling fs layer
  ef4b6175897e: Pulling fs layer
  c7f57f419954: Waiting
  f427023642b5: Waiting
  ef4b6175897e: Waiting
  3f4ca61aafcd: Verifying Checksum
  3f4ca61aafcd: Download complete
executor >  local (463)
[1e/3a2445] process > RIBAP:rename (SSA8530)      [100%] 223 of 223 ✔
[c2/a6a664] process > RIBAP:prokka (223)          [100%] 223 of 223 ✔
[10/d6133a] process > RIBAP:strain_ids            [100%] 1 of 1 ✔
[e6/e251ef] process > RIBAP:roary (1)             [100%] 5 of 5 ✔
[c4/09b2dd] process > RIBAP:mmseqs2               [100%] 1 of 1 ✔
[c7/9e51c7] process > RIBAP:mmseqs2tsv            [100%] 1 of 1 ✔
[42/b59531] process > RIBAP:ilp_refinement (5)    [ 22%] 2 of 9, failed: 1
[-        ] process > RIBAP:combine_roary_ilp     -
[-        ] process > RIBAP:prepare_msa           -
[-        ] process > RIBAP:mafft                 -
[-        ] process > RIBAP:fasttree              -
[-        ] process > RIBAP:nw_display            -
[-        ] process > RIBAP:generate_html         -
[-        ] process > RIBAP:generate_upsetr_input -
[-        ] process > RIBAP:upsetr                -
[-        ] process > RIBAP:filter_alignment      -
[-        ] process > RIBAP:nexus_core            -
[-        ] process > RIBAP:iqtree                -
ERROR ~ Error executing process > 'RIBAP:ilp_refinement (7)'

Caused by:
  Process `RIBAP:ilp_refinement (7)` terminated with an error exit status (1)


Command executed:

  derive_ilp_solutions.py --tmlim 240 --max --indel mmseqs_compressed_chunk6.pkl --keep

Command exit status:
  1

Command output:
  (empty)

Command error:
  Unable to find image 'nanozoo/python_ribap:3.7--33a36cd' locally
  3.7--33a36cd: Pulling from nanozoo/python_ribap
  3f4ca61aafcd: Pulling fs layer
  69a5d9e1ecd6: Pulling fs layer
  7b4354700ca4: Pulling fs layer
  c7f57f419954: Pulling fs layer
  f427023642b5: Pulling fs layer
  ef4b6175897e: Pulling fs layer
  c7f57f419954: Waiting
  f427023642b5: Waiting
  ef4b6175897e: Waiting
  3f4ca61aafcd: Verifying Checksum
  3f4ca61aafcd: Download complete
  c7f57f419954: Verifying Checksum
  c7f57f419954: Download complete
  3f4ca61aafcd: Pull complete
  f427023642b5: Verifying Checksum
  f427023642b5: Download complete
  69a5d9e1ecd6: Verifying Checksum
  69a5d9e1ecd6: Download complete
  7b4354700ca4: Verifying Checksum
  7b4354700ca4: Download complete
  69a5d9e1ecd6: Pull complete
  7b4354700ca4: Pull complete
  c7f57f419954: Pull complete
  f427023642b5: Pull complete
  ef4b6175897e: Verifying Checksum
  ef4b6175897e: Download complete
  ef4b6175897e: Pull complete
  Digest: sha256:3ee539be385c3495d6c84d04cb7cd5ead19f77429988cfefa88ce40efd620b96
  Status: Image is up to date for nanozoo/python_ribap:3.7--33a36cd
  Traceback (most recent call last):
    File "/root/.nextflow/assets/hoelzer-lab/ribap/bin/derive_ilp_solutions.py", line 151, in <module>
      main()
    File "/root/.nextflow/assets/hoelzer-lab/ribap/bin/derive_ilp_solutions.py", line 76, in main
      pool_workload(pairwiseSpecies, similarities)
    File "/root/.nextflow/assets/hoelzer-lab/ribap/bin/derive_ilp_solutions.py", line 113, in pool_workload
      ilpGen.generate_lp(problem, self_edge_cost=s, alpha=alpha, MATCHING_SIZE=matching_size, MAXIMAL_MATCHING=maximal, tolerance=fix_adj_tolerance, INDEL=indel)
    File "/root/.nextflow/assets/hoelzer-lab/ribap/bin/ILPBuilder.py", line 350, in generate_lp
      self.broadcast_streams(outputStreams, "c"+str(constraintID)+": " + "%s - %s - b_%s <= 0\n" % (self.edge_var(currentGene, 'h', currentGene, 't'), self.edge_var(nextGene, 'h', nextGene, 't'), currentGene))
    File "/root/.nextflow/assets/hoelzer-lab/ribap/bin/ILPBuilder.py", line 119, in broadcast_streams
      stream.write(message)
  OSError: [Errno 28] No space left on device

Work dir:
  /media/shlomo/DATADRIVE3/CoNS/CoNS_FINAL/RIBAP_work/fd/76e59f9224e2a4c2a9d79ec63bdba9

Container:
  nanozoo/python_ribap:3.7--33a36cd

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details

```

**Comment by shlomobl** [comment]
I was warned :-D

`Caused by: java.io.IOException: No space left on device`

4 TB disk?!

Is it possible to assign a new working folder in the middle of a run, to continue?
Also, is it possible to change the genomes in the analysis (add and remove) without running the whole thing again, if I do not keep ILPs?

**Comment by hoelzer** [comment]
Hey @shlomobl - yeah sorry. 

As said, the disk space and runtime are getting crazy for >100 and/or larger genomes. 

That's why we per default discard the intermediate ILP results, but you are right, you can then not `-resume` a calculation. 

> Is it possible to assign a new working folder in the middle of a run, to continue?

I don't think so 

> Also, is it possible to change the genomes in the analysis (add and remove) without running the whole thing again, if I do not keep ILPs?

As you feared, this is only possible when you keep the intermediate ILP results. 

> Last one: how can I delete ILPs? :-) The ILP file in the ILP folder (step 4) is not that big. I don't think this is the one.

Yes, the ILP files in the ILP output folder are not that big, but the ones in the `work` directories are. To free up your disk space you have to remove the `work` dir content (but then `-resume` will not work)

Sorry, I think for the moment RIBAP reaches its limits for a dataset like yours and you would need to somehow make your input smaller (pre-clustering based on ANI, POCP, ...)
